package com.example.chatroom.chat;

public enum MessageType {
    CHAT,
    JOIN,
    LEAVE,
    PRIVATE,
    GROUP,
    FRIEND_REQUEST,
    GROUP_REQUEST,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_DECLINED,
    READ_STATUS,
    USER_STATUS,
    BLOCKED,
    UNBLOCKED,
    BLOCK_CONFIRMATION,
    UNBLOCK_CONFIRMATION
}
